### ISSUE TITLE
Error in configuration button

### ISSUE THREAD

**Issue by filhocf** [EstudioNexos/mabola-blue#1]
Hi

Have some strange behavior with the config button. Follow the blue and larry screens to see the problem.

![image](https://cloud.githubusercontent.com/assets/952596/17139499/2050ed0a-531b-11e6-94c3-6a43b2c45424.png)

![image](https://cloud.githubusercontent.com/assets/952596/17139552/5fe7463a-531b-11e6-83cf-3afb7b212a13.png)

**Comment by n3storm** [comment]
I think is because Fontawesome version is a bit outdated. We are fixing this ASAP. Thanks

Fix will be done in main Mabola repository, please follow your issue at https://github.com/EstudioNexos/mabola/issues/17

**Comment by filhocf** [comment]
Hi @n3storm 
Strange. I saw that you closed this issue, but when I clicked in Issues tab, returned it as open.
Anyway, I sent a PR to close this issue.
